### ISSUE TITLE
Add firefox support

### ISSUE THREAD

**Issue by koxx12-dev** [ThatTimothy/RoNew#15]
Current release fully works when using firefox without any changes to code itself, **but** i had to add a extension id using [browser_specific_settings](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings) in manifest.json which supposedly (i cant really check) chrome does not respect and will just throw an error, so it would probably require just creating a separate src directory for firefox version if thats the case

**Comment by Timothy-Gonzalez** [comment]
Yeah, that would be my understanding as well. I'm currently looking to see if there's a nice way to do so without having two manifest files, but we'll see. If you want to make a PR to do this change in a way that ideally doesn't require two copies of src, that would be amazing.

**Comment by ThatTimothy** [comment]
Yeah, that would be my understanding as well. I'm currently looking to see if there's a nice way to do so without having two manifest files, but we'll see. If you want to make a PR to do this change in a way that ideally doesn't require two copies of src, that would be amazing.

**Comment by koxx12-dev** [comment]
forgot to attach that exact file
[ronew-2.1.3.zip](https://github.com/ThatTimothy/RoNew/files/10746190/ronew-2.1.3.zip)

**Comment by ThatTimothy** [comment]
#16 is live if you want to use it now. Just waiting for the extension to be approved by Firefox.

**Comment by ThatTimothy** [comment]
For reference, our solution for `browser_specific_settings` is just to have separate manifest files. Not the most ideal, but chrome unfortunately doesn't respect it.

**Comment by ThatTimothy** [comment]
This is live! Try the button below:

[![Firefox Extension](https://img.shields.io/amo/v/RoNew?label=Firefox%20add-ons&logo=firefox-browser&logoColor=white&style=for-the-badge&color=FF7139&cacheSeconds=3600)](https://addons.mozilla.org/addon/ronew/)
